
[env]
TERM = "xterm-256color"

[window.dimensions]
columns = 120
lines = 35

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true


[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 13

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"

[[keyboard.bindings]]
key = "Right"  
mods = "Alt"
chars = "\u001bf"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"

[[keyboard.bindings]]
key = "Right"
mods = "Command"  
chars = "\u0005"

[general]
import = [
 "~/.config/alacritty/themes/themes/coolnight.toml"
]
